/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HostelsIndexRouteImport } from './routes/hostels.index'
import { Route as BookingsIndexRouteImport } from './routes/bookings.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as HostelsIdRouteImport } from './routes/hostels.$id'
import { Route as BookingsBidRouteImport } from './routes/bookings.$bid'
import { Route as BookingIdRouteImport } from './routes/booking.$id'
import { Route as AdminRoomsRouteImport } from './routes/admin/rooms'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminHotelsRouteImport } from './routes/admin/hotels'
import { Route as AdminGalleryRouteImport } from './routes/admin/gallery'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCouponsRouteImport } from './routes/admin/coupons'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostelsIndexRoute = HostelsIndexRouteImport.update({
  id: '/hostels/',
  path: '/hostels/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const HostelsIdRoute = HostelsIdRouteImport.update({
  id: '/hostels/$id',
  path: '/hostels/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsBidRoute = BookingsBidRouteImport.update({
  id: '/bookings/$bid',
  path: '/bookings/$bid',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingIdRoute = BookingIdRouteImport.update({
  id: '/booking/$id',
  path: '/booking/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHotelsRoute = AdminHotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/hotels': typeof AdminHotelsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/booking/$id': typeof BookingIdRoute
  '/bookings/$bid': typeof BookingsBidRoute
  '/hostels/$id': typeof HostelsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/bookings/': typeof BookingsIndexRoute
  '/hostels/': typeof HostelsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/hotels': typeof AdminHotelsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/booking/$id': typeof BookingIdRoute
  '/bookings/$bid': typeof BookingsBidRoute
  '/hostels/$id': typeof HostelsIdRoute
  '/admin': typeof AdminIndexRoute
  '/bookings': typeof BookingsIndexRoute
  '/hostels': typeof HostelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/hotels': typeof AdminHotelsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/booking/$id': typeof BookingIdRoute
  '/bookings/$bid': typeof BookingsBidRoute
  '/hostels/$id': typeof HostelsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/bookings/': typeof BookingsIndexRoute
  '/hostels/': typeof HostelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/admin/bookings'
    | '/admin/coupons'
    | '/admin/dashboard'
    | '/admin/gallery'
    | '/admin/hotels'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/profile'
    | '/admin/reviews'
    | '/admin/rooms'
    | '/booking/$id'
    | '/bookings/$bid'
    | '/hostels/$id'
    | '/admin/'
    | '/bookings/'
    | '/hostels/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/admin/bookings'
    | '/admin/coupons'
    | '/admin/dashboard'
    | '/admin/gallery'
    | '/admin/hotels'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/profile'
    | '/admin/reviews'
    | '/admin/rooms'
    | '/booking/$id'
    | '/bookings/$bid'
    | '/hostels/$id'
    | '/admin'
    | '/bookings'
    | '/hostels'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/admin/bookings'
    | '/admin/coupons'
    | '/admin/dashboard'
    | '/admin/gallery'
    | '/admin/hotels'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/profile'
    | '/admin/reviews'
    | '/admin/rooms'
    | '/booking/$id'
    | '/bookings/$bid'
    | '/hostels/$id'
    | '/admin/'
    | '/bookings/'
    | '/hostels/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  BookingIdRoute: typeof BookingIdRoute
  BookingsBidRoute: typeof BookingsBidRoute
  HostelsIdRoute: typeof HostelsIdRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
  HostelsIndexRoute: typeof HostelsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hostels/': {
      id: '/hostels/'
      path: '/hostels'
      fullPath: '/hostels/'
      preLoaderRoute: typeof HostelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/hostels/$id': {
      id: '/hostels/$id'
      path: '/hostels/$id'
      fullPath: '/hostels/$id'
      preLoaderRoute: typeof HostelsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$bid': {
      id: '/bookings/$bid'
      path: '/bookings/$bid'
      fullPath: '/bookings/$bid'
      preLoaderRoute: typeof BookingsBidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$id': {
      id: '/booking/$id'
      path: '/booking/$id'
      fullPath: '/booking/$id'
      preLoaderRoute: typeof BookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hotels': {
      id: '/admin/hotels'
      path: '/hotels'
      fullPath: '/admin/hotels'
      preLoaderRoute: typeof AdminHotelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminHotelsRoute: typeof AdminHotelsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminRoomsRoute: typeof AdminRoomsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminHotelsRoute: AdminHotelsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminRoomsRoute: AdminRoomsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  BookingIdRoute: BookingIdRoute,
  BookingsBidRoute: BookingsBidRoute,
  HostelsIdRoute: HostelsIdRoute,
  BookingsIndexRoute: BookingsIndexRoute,
  HostelsIndexRoute: HostelsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
